name: api_debugger
description: Inspect Dio requests, responses, errors, headers, bodies, and timing in a modern in-app Flutter network debugger.
version: 0.1.2
homepage: https://github.com/sazzad765/ApiDebugger
repository: https://github.com/sazzad765/ApiDebugger
issue_tracker: https://github.com/sazzad765/ApiDebugger/issues

topics:
  - dio
  - debugging
  - network
  - inspector
  - flutter-devtools

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
